apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: reader-service
  name: reader-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: reader-service
    spec:
      containers:
      - image: microservice-reader:latest
        name: microservice-reader
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: reader-service
  name: reader-service
spec:
  ports:
  - name: 8082-8082
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: reader-service
  type: ClusterIP
status:
  loadBalancer: {}
